// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Greeting(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, "May be  or Hello! " + name);
}

var make = Greeting;

export {
  make ,
  
}
/* react Not a pure module */
