// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/lib/es6/src/legacy/ReactDOMRe.bs.js";
import * as Greeting$Test from "./Greeting.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Greeting$Test.make, {
          name: "John"
        }), "app");

var h = module.hot;

if (h == null) {
  console.log("We are not hot");
} else {
  h.accept();
}

export {
  
}
/*  Not a pure module */
